name: Rebuild Licence data file

on:
  push:
    branches: [ master, develop, action-tests-1 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  licence:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Check if the file is present
        run: echo running on branch ${GITHUB_REF##*/}
        id: check

      - name: Checkout the missing file
        run: git checkout -- licence-data.php
    
