name: Rebuild Licence data file

on:
  push:
    branches: [ master, develop, action-tests-1 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  licence:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Rebuild the licence-data.php file
        run: git checkout -- licence-data.php && git commit licence-data.php -m "adds missing lincence-data.php file"
